# Generated by Django 5.2.5 on 2025-10-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to='experience_certificates/'),
        ),
    ]
